repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        exclude: ^src/lib/
      - id: end-of-file-fixer
        exclude: ^src/lib/
      - id: trailing-whitespace
        exclude: ^src/lib/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
      - id: mypy
        files: ^(src|tests)/
        additional_dependencies: ["types-requests"]

  - repo: local
    hooks:
      - id: pylint-errors-only
        name: pylint (errors only)
        entry: pipenv run pylint
        language: system
        types: [python]
        args: [--errors-only, src, tests]

      - id: unit-tests
        name: unit tests
        entry: python tests/run_tests.py
        language: system
        pass_filenames: false
        always_run: true

      - id: vulture
        name: vulture (dead code detection)
        entry: pipenv run vulture
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
