# WICID System Configuration
# These settings are deployed with each firmware update

VERSION = "0.2.1"
SYSTEM_UPDATE_MANIFEST_URL = "https://www.wicid.ai/releases.json"
SYSTEM_UPDATE_CHECK_INTERVAL = 24  # hours
WEATHER_UPDATE_INTERVAL = 1200  # seconds

